# -*- coding: utf-8 -*-
"""PROYECTO_FINAL.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1dh-I8mAPsnh2n9m6BE6bQ1upMGHpJZ6e
"""

import sqlite3
import hashlib
import json
import os
import time
import random
from datetime import datetime
import pandas as pd

try:
    from IPython.display import display
except ImportError:
    display = None


# ============================================================
# CONFIGURACION
# ============================================================

DB_FILE = "fuelchain.db"
DATA_DIR = "data"
BLOCKCHAIN_FILE = os.path.join(DATA_DIR, "blockchain.json")
EVENTS_FILE = os.path.join(DATA_DIR, "events.json")
SENSORS_FILE = os.path.join(DATA_DIR, "sensors.json")


# ============================================================
# UTILIDADES
# ============================================================

class Utilidades:

    @staticmethod
    def fecha_actual():
        return datetime.now().strftime("%Y-%m-%d %H:%M:%S")

    @staticmethod
    def limpiar():
        print("\n" * 3)

    @staticmethod
    def pausa():
        input("\nPresiona ENTER para continuar...")

    @staticmethod
    def animacion(mensaje, segundos=1.0):
        print("\n" + mensaje)
        pasos = 20

        for i in range(pasos + 1):
            porcentaje = int((i / pasos) * 100)
            barra = "#" * i + "-" * (pasos - i)
            print(
                "\r[" + barra + "] " + str(porcentaje) + "%",
                end=""
            )
            time.sleep(segundos / pasos)

        print()

    @staticmethod
    def guardar_json(archivo, datos):
        try:
            with open(archivo, "w", encoding="utf-8") as file:
                json.dump(
                    datos,
                    file,
                    indent=4,
                    ensure_ascii=False
                )
        except Exception as error:
            print("\nError guardando archivo:", error)

    @staticmethod
    def leer_json(archivo):
        if not os.path.exists(archivo):
            return []

        try:
            with open(archivo, "r", encoding="utf-8") as file:
                return json.load(file)
        except Exception:
            return []


# ============================================================
# SEGURIDAD
# ============================================================

class Seguridad:

    # Simulacion educativa de una clave almacenada en hardware seguro.
    CLAVE_HSM = "HSM_FUELCHAIN_YPFB_ANH"

    @staticmethod
    def generar_firma(datos):
        contenido = json.dumps(datos, sort_keys=True)
        contenido += Seguridad.CLAVE_HSM
        return hashlib.sha256(
            contenido.encode("utf-8")
        ).hexdigest()

    @staticmethod
    def verificar_firma(datos, firma):
        firma_correcta = Seguridad.generar_firma(datos)
        return firma_correcta == firma


# ============================================================
# CLASE ENVIO
# ============================================================

class Envio:

    def __init__(self, camion, origen, destino, volumen):
        self.camion = camion
        self.origen = origen
        self.destino = destino
        self.volumen_inicial = volumen
        self.volumen_actual = volumen
        self.estado = "IN_TRANSIT"
        self.fecha = Utilidades.fecha_actual()

    def modificar_volumen(self, nuevo_volumen):
        self.volumen_actual = nuevo_volumen

    def mostrar(self):
        print("\n------------------------------------------")
        print("            INFORMACION DEL ENVIO")
        print("------------------------------------------")
        print("Camion:", self.camion)
        print("Origen:", self.origen)
        print("Destino:", self.destino)
        print("Volumen inicial:", self.volumen_inicial, "L")
        print("Volumen actual:", self.volumen_actual, "L")
        print("Estado:", self.estado)
        print("Fecha:", self.fecha)
        print("------------------------------------------")


# ============================================================
# CLASE BASE DE DATOS
# ============================================================

class BaseDatos:

    def __init__(self, archivo):
        self.archivo = archivo
        self.conexion = sqlite3.connect(self.archivo)
        self.conexion.execute("PRAGMA foreign_keys = ON")
        self.crear_tablas()

    # --------------------------------------------------------
    # CREAR TABLAS
    # --------------------------------------------------------

    def crear_tablas(self):
        cursor = self.conexion.cursor()

        cursor.execute("""
            CREATE TABLE IF NOT EXISTS camiones (
                id INTEGER PRIMARY KEY AUTOINCREMENT,
                placa TEXT UNIQUE NOT NULL,
                conductor TEXT,
                capacidad REAL,
                estado TEXT,
                fecha_registro TEXT
            )
        """)

        cursor.execute("""
            CREATE TABLE IF NOT EXISTS envios (
                id INTEGER PRIMARY KEY AUTOINCREMENT,
                camion_id INTEGER NOT NULL,
                origen TEXT NOT NULL,
                destino TEXT NOT NULL,
                volumen_inicial REAL,
                volumen_actual REAL,
                estado TEXT,
                fecha TEXT,
                FOREIGN KEY(camion_id) REFERENCES camiones(id)
            )
        """)

        cursor.execute("""
            CREATE TABLE IF NOT EXISTS sensores (
                id INTEGER PRIMARY KEY AUTOINCREMENT,
                envio_id INTEGER NOT NULL,
                camion_id INTEGER NOT NULL,
                volumen REAL,
                densidad REAL,
                temperatura REAL,
                latitud REAL,
                longitud REAL,
                firma TEXT,
                fecha TEXT,
                FOREIGN KEY(envio_id) REFERENCES envios(id),
                FOREIGN KEY(camion_id) REFERENCES camiones(id)
            )
        """)

        cursor.execute("""
            CREATE TABLE IF NOT EXISTS eventos (
                id INTEGER PRIMARY KEY AUTOINCREMENT,
                envio_id INTEGER,
                tipo TEXT,
                descripcion TEXT,
                severidad TEXT,
                fecha TEXT,
                FOREIGN KEY(envio_id) REFERENCES envios(id)
            )
        """)

        cursor.execute("""
            CREATE TABLE IF NOT EXISTS bloques (
                id INTEGER PRIMARY KEY AUTOINCREMENT,
                numero INTEGER UNIQUE,
                evento TEXT,
                datos TEXT,
                hash_anterior TEXT,
                hash_actual TEXT,
                fecha TEXT
            )
        """)

        self.conexion.commit()

    # --------------------------------------------------------
    # CAMIONES
    # --------------------------------------------------------

    def insertar_camion(self, placa, conductor, capacidad):
        cursor = self.conexion.cursor()

        try:
            cursor.execute("""
                INSERT INTO camiones
                (placa, conductor, capacidad, estado, fecha_registro)
                VALUES (?, ?, ?, ?, ?)
            """, (
                placa,
                conductor,
                capacidad,
                "DISPONIBLE",
                Utilidades.fecha_actual()
            ))
            self.conexion.commit()
            return cursor.lastrowid

        except sqlite3.IntegrityError:
            cursor.execute(
                "SELECT id FROM camiones WHERE placa = ?",
                (placa,)
            )
            resultado = cursor.fetchone()
            return resultado[0]

    # --------------------------------------------------------
    # ENVIOS
    # --------------------------------------------------------

    def insertar_envio(self, envio):
        camion_id = self.obtener_camion_id(envio.camion)
        cursor = self.conexion.cursor()

        cursor.execute("""
            INSERT INTO envios
            (camion_id, origen, destino, volumen_inicial,
             volumen_actual, estado, fecha)
            VALUES (?, ?, ?, ?, ?, ?, ?)
        """, (
            camion_id,
            envio.origen,
            envio.destino,
            envio.volumen_inicial,
            envio.volumen_actual,
            envio.estado,
            envio.fecha
        ))

        self.conexion.commit()
        return cursor.lastrowid

    def actualizar_volumen_envio(self, envio_id, volumen):
        cursor = self.conexion.cursor()
        cursor.execute("""
            UPDATE envios
            SET volumen_actual = ?
            WHERE id = ?
        """, (volumen, envio_id))
        self.conexion.commit()

    def actualizar_estado_envio(self, envio_id, estado):
        cursor = self.conexion.cursor()
        cursor.execute("""
            UPDATE envios
            SET estado = ?
            WHERE id = ?
        """, (estado, envio_id))
        self.conexion.commit()

    # --------------------------------------------------------
    # OBTENER CAMION
    # --------------------------------------------------------

    def obtener_camion_id(self, placa):
        cursor = self.conexion.cursor()
        cursor.execute(
            "SELECT id FROM camiones WHERE placa = ?",
            (placa,)
        )
        resultado = cursor.fetchone()

        if resultado:
            return resultado[0]

        return self.insertar_camion(
            placa,
            "Conductor Demo",
            20000
        )

    # --------------------------------------------------------
    # SENSORES
    # --------------------------------------------------------

    def insertar_sensor(self, lectura):
        camion_id = self.obtener_camion_id(lectura["camion"])
        cursor = self.conexion.cursor()

        cursor.execute("""
            INSERT INTO sensores
            (envio_id, camion_id, volumen, densidad, temperatura,
             latitud, longitud, firma, fecha)
            VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)
        """, (
            lectura["envio_id"],
            camion_id,
            lectura["volumen"],
            lectura["densidad"],
            lectura["temperatura"],
            lectura["latitud"],
            lectura["longitud"],
            lectura["firma"],
            lectura["fecha"]
        ))

        self.conexion.commit()

    # --------------------------------------------------------
    # EVENTOS
    # --------------------------------------------------------

    def insertar_evento(self, envio_id, tipo, descripcion, severidad):
        cursor = self.conexion.cursor()

        cursor.execute("""
            INSERT INTO eventos
            (envio_id, tipo, descripcion, severidad, fecha)
            VALUES (?, ?, ?, ?, ?)
        """, (
            envio_id,
            tipo,
            descripcion,
            severidad,
            Utilidades.fecha_actual()
        ))

        self.conexion.commit()
        return cursor.lastrowid

    # --------------------------------------------------------
    # BLOCKCHAIN
    # --------------------------------------------------------

    def insertar_bloque(self, bloque):
        cursor = self.conexion.cursor()

        cursor.execute("""
            INSERT INTO bloques
            (numero, evento, datos, hash_anterior, hash_actual, fecha)
            VALUES (?, ?, ?, ?, ?, ?)
        """, (
            bloque["numero"],
            bloque["evento"],
            json.dumps(bloque["datos"], sort_keys=True),
            bloque["hash_anterior"],
            bloque["hash_actual"],
            bloque["fecha"]
        ))

        self.conexion.commit()

    def obtener_ultimo_hash(self):
        cursor = self.conexion.cursor()
        cursor.execute("""
            SELECT hash_actual
            FROM bloques
            ORDER BY numero DESC
            LIMIT 1
        """)
        resultado = cursor.fetchone()
        return "GENESIS" if resultado is None else resultado[0]

    def obtener_numero_bloque(self):
        cursor = self.conexion.cursor()
        cursor.execute("SELECT MAX(numero) FROM bloques")
        resultado = cursor.fetchone()
        return 0 if resultado[0] is None else resultado[0] + 1

    # --------------------------------------------------------
    # CONSULTAS
    # --------------------------------------------------------

    def contar_bloques(self):
        return self.conexion.execute(
            "SELECT COUNT(*) FROM bloques"
        ).fetchone()[0]

    def contar_sensores(self):
        return self.conexion.execute(
            "SELECT COUNT(*) FROM sensores"
        ).fetchone()[0]

    def contar_eventos(self):
        return self.conexion.execute(
            "SELECT COUNT(*) FROM eventos"
        ).fetchone()[0]

    def contar_envios(self):
        return self.conexion.execute(
            "SELECT COUNT(*) FROM envios"
        ).fetchone()[0]

    def contar_alertas(self):
        return self.conexion.execute("""
            SELECT COUNT(*) FROM eventos
            WHERE severidad = 'CRITICA'
        """).fetchone()[0]

    def obtener_envios(self):
        cursor = self.conexion.cursor()
        cursor.execute("""
            SELECT
                envios.id,
                camiones.placa,
                envios.origen,
                envios.destino,
                envios.volumen_inicial,
                envios.volumen_actual,
                envios.estado,
                envios.fecha
            FROM envios
            INNER JOIN camiones
                ON envios.camion_id = camiones.id
            ORDER BY envios.id DESC
        """)
        return cursor.fetchall()

    def obtener_sensores(self):
        cursor = self.conexion.cursor()
        cursor.execute("""
            SELECT
                id,
                envio_id,
                volumen,
                densidad,
                temperatura,
                latitud,
                longitud,
                firma,
                fecha
            FROM sensores
            ORDER BY id DESC
        """)
        return cursor.fetchall()

    def obtener_eventos(self):
        cursor = self.conexion.cursor()
        cursor.execute("""
            SELECT
                id,
                envio_id,
                tipo,
                descripcion,
                severidad,
                fecha
            FROM eventos
            ORDER BY id DESC
        """)
        return cursor.fetchall()

    def obtener_bloques(self):
        cursor = self.conexion.cursor()
        cursor.execute("""
            SELECT
                numero,
                evento,
                datos,
                hash_anterior,
                hash_actual,
                fecha
            FROM bloques
            ORDER BY numero ASC
        """)
        return cursor.fetchall()

    # --------------------------------------------------------
    # NUEVO: DATAFRAMES PARA GOOGLE COLAB
    # --------------------------------------------------------

    def obtener_dataframe(self, tabla):
        """Lee una tabla SQLite directamente como DataFrame de Pandas."""
        tablas_permitidas = {
            "camiones",
            "envios",
            "sensores",
            "eventos",
            "bloques"
        }

        if tabla not in tablas_permitidas:
            raise ValueError("Tabla no permitida")

        return pd.read_sql_query(
            f"SELECT * FROM {tabla}",
            self.conexion
        )

    def mostrar_tabla_pandas(self, tabla):
        """Muestra una tabla SQLite de forma visual en Google Colab."""
        try:
            df = self.obtener_dataframe(tabla)

            print("\n" + "=" * 100)
            print(f" TABLA SQLITE: {tabla.upper()} | PANDAS")
            print("=" * 100)

            if df.empty:
                print("\nLa tabla esta vacia.")
                return

            if display is not None:
                display(df)
            else:
                print(df.to_string(index=False))

            print(f"\nRegistros mostrados: {len(df)}")

        except Exception as error:
            print("Error mostrando la tabla:", error)

    def mostrar_bd_pandas(self):
        """Muestra todas las tablas principales de FuelChain con Pandas."""
        tablas = [
            "camiones",
            "envios",
            "sensores",
            "eventos",
            "bloques"
        ]

        print("\n")
        print("=" * 100)
        print("                    FUELCHAIN BOLIVIA - BASE DE DATOS")
        print("                    SQLITE + PANDAS / GOOGLE COLAB")
        print("=" * 100)

        for tabla in tablas:
            self.mostrar_tabla_pandas(tabla)

    def cerrar(self):
        self.conexion.close()


# ============================================================
# CLASE SENSOR
# ============================================================

class Sensor:

    def __init__(self, camion):
        self.camion = camion
        self.densidad = 0.74
        self.temperatura = 20.0

    def leer(self, envio_id, volumen, latitud, longitud):
        datos = {
            "envio_id": envio_id,
            "camion": self.camion,
            "volumen": volumen,
            "densidad": self.densidad,
            "temperatura": self.temperatura,
            "latitud": latitud,
            "longitud": longitud
        }

        firma = Seguridad.generar_firma(datos)

        return {
            "envio_id": envio_id,
            "camion": self.camion,
            "volumen": volumen,
            "densidad": self.densidad,
            "temperatura": self.temperatura,
            "latitud": latitud,
            "longitud": longitud,
            "firma": firma,
            "fecha": Utilidades.fecha_actual()
        }


# ============================================================
# BLOCKCHAIN
# ============================================================

class Blockchain:

    def __init__(self, base_datos):
        self.base_datos = base_datos
        self.archivo = BLOCKCHAIN_FILE

    def crear_bloque(self, evento, datos):
        numero = self.base_datos.obtener_numero_bloque()
        hash_anterior = self.base_datos.obtener_ultimo_hash()
        fecha = Utilidades.fecha_actual()

        informacion = {
            "numero": numero,
            "evento": evento,
            "datos": datos,
            "hash_anterior": hash_anterior,
            "fecha": fecha
        }

        contenido = json.dumps(informacion, sort_keys=True)
        hash_actual = hashlib.sha256(
            contenido.encode("utf-8")
        ).hexdigest()

        bloque = {
            "numero": numero,
            "evento": evento,
            "datos": datos,
            "hash_anterior": hash_anterior,
            "hash_actual": hash_actual,
            "fecha": fecha
        }

        self.base_datos.insertar_bloque(bloque)
        self.exportar_json()
        return bloque

    def exportar_json(self):
        bloques_db = self.base_datos.obtener_bloques()
        bloques = []

        for bloque in bloques_db:
            bloques.append({
                "numero": bloque[0],
                "evento": bloque[1],
                "datos": json.loads(bloque[2]),
                "hash_anterior": bloque[3],
                "hash_actual": bloque[4],
                "fecha": bloque[5]
            })

        Utilidades.guardar_json(self.archivo, bloques)

    def mostrar(self):
        bloques = self.base_datos.obtener_bloques()

        print("\n")
        print("=" * 80)
        print(" BLOCKCHAIN")
        print("=" * 80)

        if not bloques:
            print("\nBlockchain vacia.")
            return

        for bloque in bloques:
            print("\nBloque:", bloque[0])
            print("Evento:", bloque[1])
            print("Hash anterior:", bloque[3][:30] + "...")
            print("Hash actual:", bloque[4][:30] + "...")
            print("Fecha:", bloque[5])
            print("-" * 80)

    def verificar_integridad(self):
        bloques = self.base_datos.obtener_bloques()

        if not bloques:
            print("\nBlockchain vacia.")
            return True

        hash_anterior_esperado = "GENESIS"
        correcto = True

        for bloque in bloques:
            numero = bloque[0]
            evento = bloque[1]
            datos = json.loads(bloque[2])
            hash_anterior = bloque[3]
            hash_actual = bloque[4]
            fecha = bloque[5]

            informacion = {
                "numero": numero,
                "evento": evento,
                "datos": datos,
                "hash_anterior": hash_anterior,
                "fecha": fecha
            }

            contenido = json.dumps(informacion, sort_keys=True)
            hash_calculado = hashlib.sha256(
                contenido.encode("utf-8")
            ).hexdigest()

            if hash_anterior != hash_anterior_esperado:
                correcto = False

            if hash_calculado != hash_actual:
                correcto = False

            hash_anterior_esperado = hash_actual

        print("\n")
        print("=" * 70)
        print(" VERIFICACION BLOCKCHAIN")
        print("=" * 70)

        if correcto:
            print("\n[OK] Blockchain integra.")
            print("[OK] Hashes correctos.")
            print("[OK] Cadena sin alteraciones.")
        else:
            print("\n[ERROR] Blockchain alterada.")
            print("[ERROR] Se detecto inconsistencia.")

        return correcto


# ============================================================
# SISTEMA DE ALERTAS
# ============================================================

class SistemaAlertas:

    def __init__(self, base_datos):
        self.base_datos = base_datos

    def generar_alerta(
        self,
        envio_id,
        mensaje,
        tipo="SECURITY_ALERT",
        severidad="CRITICA"
    ):
        evento_id = self.base_datos.insertar_evento(
            envio_id,
            tipo,
            mensaje,
            severidad
        )
        self.exportar()
        return evento_id

    def exportar(self):
        eventos_db = self.base_datos.obtener_eventos()
        eventos = []

        for evento in eventos_db:
            eventos.append({
                "id": evento[0],
                "envio_id": evento[1],
                "tipo": evento[2],
                "descripcion": evento[3],
                "severidad": evento[4],
                "fecha": evento[5]
            })

        Utilidades.guardar_json(EVENTS_FILE, eventos)

    def mostrar_alertas(self):
        eventos = self.base_datos.obtener_eventos()

        print("\n")
        print("=" * 80)
        print(" EVENTOS")
        print("=" * 80)

        if not eventos:
            print("\nNo existen eventos.")
            return

        for evento in eventos:
            print("\nID:", evento[0])
            print("Envio:", evento[1])
            print("Tipo:", evento[2])
            print("Descripcion:", evento[3])
            print("Severidad:", evento[4])
            print("Fecha:", evento[5])
            print("-" * 80)


# ============================================================
# CONTROL DE ENTREGA
# ============================================================

class ControlEntrega:

    def __init__(self, base_datos):
        self.base_datos = base_datos

    def verificar(
        self,
        envio_id,
        gps_correcto,
        tanque_disponible,
        firma_correcta,
        precinto_correcto
    ):
        print("\n")
        print("=" * 70)
        print(" DUAL HANDSHAKE DELIVERY")
        print("=" * 70)
        print("\nVerificando condiciones...\n")

        time.sleep(0.5)
        print("[1] GPS:", "OK" if gps_correcto else "FALLO")
        time.sleep(0.5)
        print("[2] Tanque receptor:", "OK" if tanque_disponible else "FALLO")
        time.sleep(0.5)
        print("[3] Firma HSM:", "OK" if firma_correcta else "FALLO")
        time.sleep(0.5)
        print("[4] Precinto:", "OK" if precinto_correcto else "FALLO")

        autorizado = (
            gps_correcto
            and tanque_disponible
            and firma_correcta
            and precinto_correcto
        )

        print("\n")

        if autorizado:
            print("==========================================")
            print(" ENTREGA AUTORIZADA")
            print("==========================================")
            print("\nValvula: ABIERTA")
            print("Combustible: AUTORIZADO")
            self.base_datos.actualizar_estado_envio(
                envio_id,
                "DELIVERED"
            )
        else:
            print("==========================================")
            print(" ENTREGA BLOQUEADA")
            print("==========================================")
            print("\nValvula: CERRADA")
            print("Combustible: NO AUTORIZADO")
            self.base_datos.actualizar_estado_envio(
                envio_id,
                "BLOCKED"
            )

        return autorizado


# ============================================================
# SIMULADOR
# ============================================================

class Simulador:

    def __init__(self, base_datos, blockchain, alertas):
        self.base_datos = base_datos
        self.blockchain = blockchain
        self.alertas = alertas
        self.envio_actual_id = None
        self.volumen_actual = 0

    def crear_envio(self):
        camion = "TRUCK-LPZ-001"

        self.base_datos.insertar_camion(
            camion,
            "Conductor Demo",
            20000
        )

        envio = Envio(
            camion,
            "Planta de Senkata",
            "Estacion La Paz",
            20000
        )

        envio_id = self.base_datos.insertar_envio(envio)
        self.envio_actual_id = envio_id
        self.volumen_actual = envio.volumen_actual

        datos = {
            "envio_id": envio_id,
            "camion": envio.camion,
            "origen": envio.origen,
            "destino": envio.destino,
            "volumen": envio.volumen_inicial
        }

        bloque = self.blockchain.crear_bloque(
            "MINT_FUEL_BATCH",
            datos
        )

        print("\n")
        print("=" * 70)
        print(" LOTE CREADO")
        print("=" * 70)
        print("\nID envio:", envio_id)
        print("Camion:", envio.camion)
        print("Volumen:", envio.volumen_inicial, "L")
        print("Origen:", envio.origen)
        print("Destino:", envio.destino)
        print("\nPrecintos: LOCKED")
        print("\nHash:", bloque["hash_actual"][:40] + "...")

        Utilidades.pausa()

    def verificar_envio(self):
        if self.envio_actual_id is None:
            print("\nPrimero debes crear un lote.")
            Utilidades.pausa()
            return False
        return True

    def viaje(self):
        if not self.verificar_envio():
            return

        sensor = Sensor("TRUCK-LPZ-001")

        ruta = [
            ("Senkata", -16.515, -68.193),
            ("El Alto", -16.500, -68.150),
            ("Autopista", -16.510, -68.140),
            ("La Paz", -16.495, -68.145),
            ("Estacion destino", -16.500, -68.150)
        ]

        print("\n")
        print("=" * 70)
        print(" SIMULACION SENKATA -> LA PAZ")
        print("=" * 70)

        for lugar, lat, lon in ruta:
            perdida_normal = random.randint(10, 30)
            self.volumen_actual -= perdida_normal

            print("\n------------------------------------------")
            print("Ubicacion:", lugar)

            Utilidades.animacion("Leyendo sensores...", 0.8)

            lectura = sensor.leer(
                self.envio_actual_id,
                self.volumen_actual,
                lat,
                lon
            )

            self.base_datos.insertar_sensor(lectura)

            self.base_datos.actualizar_volumen_envio(
                self.envio_actual_id,
                self.volumen_actual
            )

            self.blockchain.crear_bloque(
                "SENSOR_READING",
                lectura
            )

            print("Volumen:", self.volumen_actual, "L")
            print("Densidad:", lectura["densidad"])
            print("Temperatura:", lectura["temperatura"], "C")
            print("GPS:", lat, lon)
            print("Firma HSM: VALIDA")
            print("SQLite: GUARDADO")
            print("Blockchain: REGISTRADO")
            print("Precinto: LOCKED")

        self.base_datos.actualizar_estado_envio(
            self.envio_actual_id,
            "AT_DESTINATION"
        )

        print("\nTRANSPORTE FINALIZADO")
        print("Volumen final:", self.volumen_actual, "L")
        Utilidades.pausa()

    def ordeno(self):
        if not self.verificar_envio():
            return

        print("\n")
        print("=" * 70)
        print(" SIMULACION DE ORDENO")
        print("=" * 70)

        volumen_esperado = self.volumen_actual
        volumen_detectado = volumen_esperado - 4000

        print("\nVolumen esperado:", volumen_esperado, "L")
        Utilidades.animacion("Monitoreando volumen...", 1.5)
        print("\nVolumen detectado:", volumen_detectado, "L")

        diferencia = volumen_esperado - volumen_detectado
        print("\nDiferencia:", diferencia, "L")

        if diferencia > 1000:
            print("\n")
            print("!" * 42)
            print(" ALERTA DE SEGURIDAD")
            print("!" * 42)
            print("\nPosible ordeño/sifonamiento detectado.")

            self.base_datos.actualizar_volumen_envio(
                self.envio_actual_id,
                volumen_detectado
            )

            self.base_datos.actualizar_estado_envio(
                self.envio_actual_id,
                "BLOCKED"
            )

            self.alertas.generar_alerta(
                self.envio_actual_id,
                "Variacion anormal de volumen detectada",
                "SUSPECTED_TAMPER",
                "CRITICA"
            )

            datos = {
                "envio_id": self.envio_actual_id,
                "camion": "TRUCK-LPZ-001",
                "volumen_esperado": volumen_esperado,
                "volumen_detectado": volumen_detectado,
                "diferencia": diferencia,
                "accion": "DELIVERY_BLOCKED"
            }

            bloque = self.blockchain.crear_bloque(
                "SUSPECTED_TAMPER",
                datos
            )

            print("\nPrecintos: LOCKED")
            print("Entrega: BLOCKED")
            print("ANH: ALERTA")
            print("SQLite: EVENTO GUARDADO")
            print("Blockchain: EVENTO REGISTRADO")
            print("\nHash:", bloque["hash_actual"][:40] + "...")

        Utilidades.pausa()

    def ataque_sensor(self):
        if not self.verificar_envio():
            return

        print("\n")
        print("=" * 70)
        print(" ATAQUE AL SENSOR")
        print("=" * 70)

        datos_originales = {
            "envio_id": self.envio_actual_id,
            "camion": "TRUCK-LPZ-001",
            "volumen": self.volumen_actual,
            "densidad": 0.74,
            "temperatura": 20.0,
            "latitud": -16.510,
            "longitud": -68.140
        }

        firma_original = Seguridad.generar_firma(datos_originales)

        print("\nVolumen real:", datos_originales["volumen"], "L")
        print("Firma original:", firma_original[:30] + "...")

        Utilidades.animacion(
            "Atacante modificando informacion...",
            1.5
        )

        datos_modificados = datos_originales.copy()
        datos_modificados["volumen"] = 20000

        print("\nNuevo volumen:", datos_modificados["volumen"], "L")

        Utilidades.animacion(
            "HSM verificando firma...",
            1.5
        )

        firma_valida = Seguridad.verificar_firma(
            datos_modificados,
            firma_original
        )

        print("\n")

        if not firma_valida:
            print("!" * 42)
            print("       TRANSACCION RECHAZADA")
            print("!" * 42)
            print("\nFirma: INVALIDA")
            print("Datos: MANIPULADOS")
            print("Entrega: BLOCKED")
            print("Precintos: LOCKED")

            self.base_datos.actualizar_estado_envio(
                self.envio_actual_id,
                "BLOCKED"
            )

            datos = {
                "envio_id": self.envio_actual_id,
                "camion": "TRUCK-LPZ-001",
                "evento": "HSM_SIGNATURE_FAILURE",
                "accion": "DELIVERY_BLOCKED"
            }

            self.blockchain.crear_bloque(
                "HSM_SIGNATURE_FAILURE",
                datos
            )

            self.alertas.generar_alerta(
                self.envio_actual_id,
                "Intento de manipulacion de datos del sensor",
                "HSM_SIGNATURE_FAILURE",
                "CRITICA"
            )

            print("\nSQLite: EVENTO GUARDADO")
            print("Blockchain: EVENTO REGISTRADO")
        else:
            print("\nFirma valida.")

        Utilidades.pausa()

    def entrega(self):
        if not self.verificar_envio():
            return

        control = ControlEntrega(self.base_datos)

        autorizado = control.verificar(
            self.envio_actual_id,
            gps_correcto=True,
            tanque_disponible=True,
            firma_correcta=True,
            precinto_correcto=True
        )

        if autorizado:
            self.blockchain.crear_bloque(
                "DELIVERY_AUTHORIZED",
                {
                    "envio_id": self.envio_actual_id,
                    "camion": "TRUCK-LPZ-001",
                    "destino": "Estacion La Paz",
                    "estado": "AUTHORIZED"
                }
            )

        Utilidades.pausa()


# ============================================================
# FUELCHAIN
# ============================================================

class FuelChain:

    def __init__(self):
        self.preparar_archivos()

        self.base_datos = BaseDatos(DB_FILE)
        self.blockchain = Blockchain(self.base_datos)
        self.alertas = SistemaAlertas(self.base_datos)

        self.simulador = Simulador(
            self.base_datos,
            self.blockchain,
            self.alertas
        )

    def preparar_archivos(self):
        if not os.path.exists(DATA_DIR):
            os.makedirs(DATA_DIR)

        archivos = [
            BLOCKCHAIN_FILE,
            EVENTS_FILE,
            SENSORS_FILE
        ]

        for archivo in archivos:
            if not os.path.exists(archivo):
                Utilidades.guardar_json(archivo, [])

    # ========================================================
    # DASHBOARD
    # ========================================================

    def dashboard(self):
        print("\n")
        print("=" * 75)
        print("                         FUELCHAIN")
        print("                    CONTROL CENTER")
        print("=" * 75)

        print("\nSISTEMA")
        print("------------------------------------------")
        print("Sensores IoT:         [ ONLINE ]")
        print("HSM:                  [ SECURE ]")
        print("Blockchain:           [ ONLINE ]")
        print("SQLite:               [ ONLINE ]")

        print("\nESTADISTICAS")
        print("------------------------------------------")
        print("Envios:", self.base_datos.contar_envios())
        print("Lecturas sensores:", self.base_datos.contar_sensores())
        print("Eventos:", self.base_datos.contar_eventos())
        print("Alertas criticas:", self.base_datos.contar_alertas())
        print("Bloques:", self.base_datos.contar_bloques())

        print("\nCUSTODIA")
        print("------------------------------------------")
        print("Origen:         Planta de Senkata")
        print("Destino:        La Paz")
        print("Camion:         TRUCK-LPZ-001")
        print("Base datos:     fuelchain.db")
        print("Precintos:      LOCKED")
        print("------------------------------------------")

        Utilidades.pausa()

    # ========================================================
    # MOSTRAR ENVIOS - TERMINAL
    # ========================================================

    def mostrar_base_datos(self):
        registros = self.base_datos.obtener_envios()

        print("\n")
        print("=" * 90)
        print("                              ENVIOS")
        print("=" * 90)

        if not registros:
            print("\nNo existen envios.")
        else:
            for registro in registros:
                print("\nID:", registro[0])
                print("Camion:", registro[1])
                print("Origen:", registro[2])
                print("Destino:", registro[3])
                print("Volumen inicial:", registro[4], "L")
                print("Volumen actual:", registro[5], "L")
                print("Estado:", registro[6])
                print("Fecha:", registro[7])
                print("-" * 90)

        Utilidades.pausa()

    # ========================================================
    # MOSTRAR SENSORES - TERMINAL
    # ========================================================

    def mostrar_sensores(self):
        registros = self.base_datos.obtener_sensores()

        print("\n")
        print("=" * 100)
        print("                         LECTURAS DE SENSORES")
        print("=" * 100)

        if not registros:
            print("\nNo existen lecturas.")
        else:
            for registro in registros:
                print("\nID:", registro[0])
                print("Envio:", registro[1])
                print("Volumen:", registro[2], "L")
                print("Densidad:", registro[3])
                print("Temperatura:", registro[4], "C")
                print("GPS:", registro[5], ",", registro[6])
                print("Firma:", registro[7][:30] + "...")
                print("Fecha:", registro[8])
                print("-" * 100)

        Utilidades.pausa()

    # ========================================================
    # NUEVO: BASE DE DATOS VISUAL CON PANDAS
    # ========================================================

    def visualizar_bd_pandas(self):
        """
        NUEVA FUNCION PARA GOOGLE COLAB.

        Lee directamente fuelchain.db y muestra las tablas SQLite
        como DataFrames de Pandas.
        """
        self.base_datos.mostrar_bd_pandas()
        Utilidades.pausa()

    def visualizar_tabla_pandas(self):
        """Permite elegir una tabla concreta para visualizarla con Pandas."""
        tablas = {
            "1": "camiones",
            "2": "envios",
            "3": "sensores",
            "4": "eventos",
            "5": "bloques"
        }

        print("\n")
        print("=" * 70)
        print(" VISUALIZAR TABLA SQLITE CON PANDAS")
        print("=" * 70)
        print("1. Camiones")
        print("2. Envios")
        print("3. Sensores")
        print("4. Eventos")
        print("5. Bloques")
        print("0. Volver")

        opcion = input("\nSeleccione una tabla: ")

        if opcion == "0":
            return

        if opcion in tablas:
            self.base_datos.mostrar_tabla_pandas(tablas[opcion])
            Utilidades.pausa()
        else:
            print("\nOpcion no valida.")
            time.sleep(1)

    # ========================================================
    # INTEGRIDAD
    # ========================================================

    def verificar_blockchain(self):
        self.blockchain.verificar_integridad()
        Utilidades.pausa()

    # ========================================================
    # MENU
    # ========================================================

    def menu(self):
        while True:
            Utilidades.limpiar()

            print("=" * 75)
            print("                       FUELCHAIN BOLIVIA")
            print("                  CUSTODIA DIGITAL DE COMBUSTIBLE")
            print("                       SENKATA -> LA PAZ")
            print("=" * 75)

            print("\nMENU PRINCIPAL")
            print("------------------------------------------")
            print("1. Crear lote de combustible")
            print("2. Simular transporte")
            print("3. Simular ordeño")
            print("4. Simular ataque al sensor")
            print("5. Ejecutar Dual Handshake")
            print("6. Ver Blockchain")
            print("7. Ver envios en SQLite")
            print("8. Ver lecturas de sensores")
            print("9. Ver eventos y alertas")
            print("10. Dashboard")
            print("11. Verificar integridad Blockchain")
            print("12. VER BASE DE DATOS CON PANDAS")
            print("13. Ver una tabla con Pandas")
            print("0. Salir")
            print("------------------------------------------")

            opcion = input("\nSeleccione una opcion: ")

            if opcion == "1":
                self.simulador.crear_envio()

            elif opcion == "2":
                self.simulador.viaje()

            elif opcion == "3":
                self.simulador.ordeno()

            elif opcion == "4":
                self.simulador.ataque_sensor()

            elif opcion == "5":
                self.simulador.entrega()

            elif opcion == "6":
                self.blockchain.mostrar()
                Utilidades.pausa()

            elif opcion == "7":
                self.mostrar_base_datos()

            elif opcion == "8":
                self.mostrar_sensores()

            elif opcion == "9":
                self.alertas.mostrar_alertas()
                Utilidades.pausa()

            elif opcion == "10":
                self.dashboard()

            elif opcion == "11":
                self.verificar_blockchain()

            elif opcion == "12":
                self.visualizar_bd_pandas()

            elif opcion == "13":
                self.visualizar_tabla_pandas()

            elif opcion == "0":
                print("\nCerrando FUELCHAIN...")
                time.sleep(1)
                self.base_datos.cerrar()
                print("Sistema finalizado.")
                break

            else:
                print("\nOpcion no valida.")
                time.sleep(1)


# ============================================================
# PROGRAMA PRINCIPAL
# ============================================================

def main():
    sistema = FuelChain()
    sistema.menu()


if __name__ == "__main__":
    main()
